const songs = [
  // Indie / Dream Pop / Bedroom Pop / Psych
  { artist: "Two Door Cinema Club", title: "Undercover Martyn" },
  { artist: "Two Door Cinema Club", title: "What You Know" },
  { artist: "Two Door Cinema Club", title: "Sun" },
  { artist: "Wallows", title: "Are You Bored Yet? (feat. Clairo)" },
  { artist: "Wallows", title: "Remember When" },
  { artist: "Wallows", title: "Quarterback" },
  { artist: "Wallows", title: "Scrawny" },
  { artist: "Wallows", title: "Calling After Me" },
  { artist: "Royel Otis", title: "car" },
  { artist: "Royel Otis", title: "Oysters In My Pocket" },
  { artist: "Royel Otis", title: "Kool Aid" },
  { artist: "Royel Otis", title: "who's your boyfriend" },
  { artist: "Dayglow", title: "Hot Rod" },
  { artist: "Dayglow", title: "Close To You" },
  { artist: "Dominic Fike", title: "Westcoast Collective" },
  { artist: "JAWNY", title: "adios" },
  { artist: "JAWNY", title: "Honeypie" },
  { artist: "Foster The People", title: "Waste" },
  { artist: "BØRNS", title: "Electric Love" },
  { artist: "almost monday", title: "can't slow down" },
  { artist: "Djo", title: "Link" },
  { artist: "Djo", title: "Change" },
  { artist: "INOHA", title: "I Should've Known" },
  { artist: "INOHA", title: "GESHUOU" },
  { artist: "INOHA", title: "ALUCARDA" },
  { artist: "Malcolm Todd", title: "You Owe Me" },
  { artist: "Malcolm Todd", title: "Mr. Incorrect" },
  { artist: "Malcolm Todd", title: "I Saw Your Face" },
  { artist: "Malcolm Todd", title: "4Me 4Me" },
  { artist: "Malcolm Todd", title: "Hot in NY" },
  { artist: "Ax and the Hatchetmen", title: "Stay // Honestly" },
  { artist: "Ax and the Hatchetmen", title: "Blurry Lights (with Albert Hammond Jr)" },
  { artist: "Housecall", title: "Mystery Girl" },
  { artist: "Freak Slug", title: "Friday" },
  { artist: "Phoneboy", title: "Nevermind" },
  { artist: "Jordan Isaiah", title: "The Garden State Groove" },
  { artist: "mcgwn", title: "MOTION SICKNESS" },

  // Alt-Rock / Classic Rock / Pop-Punk / Indie Pop
  { artist: "The Killers", title: "Somebody Told Me" },
  { artist: "Weezer", title: "Say It Ain't So" },
  { artist: "Weezer", title: "Happy Hour" },
  { artist: "alt-J", title: "Left Hand Free" },
  { artist: "Red Hot Chili Peppers", title: "Sick Love" },
  { artist: "Phoenix", title: "Fences" },
  { artist: "The Black Keys", title: "Tighten Up" },
  { artist: "The Black Keys", title: "Lo/Hi" },
  { artist: "The Black Keys", title: "Gold on the Ceiling" },
  { artist: "Third Eye Blind", title: "Semi-Charmed Life" },
  { artist: "Jimmy Eat World", title: "The Middle" },
  { artist: "R.E.M.", title: "Shiny Happy People" },
  { artist: "Gorillaz feat. De La Soul", title: "Feel Good Inc." },
  { artist: "Jack Johnson", title: "Upside Down" },
  { artist: "The Beatles", title: "Don't Let Me Down" },
  { artist: "Mac Miller feat. Empire Of The Sun", title: "The Spins" },
  { artist: "Wiz Khalifa feat. Empire Of The Sun", title: "The Thrill" },

  // Hip-Hop / Rap / R&B
  { artist: "Tyler, The Creator", title: "Ring Ring Ring" },
  { artist: "Tyler, The Creator", title: "Don't You Worry Baby" },
  { artist: "Tyler, The Creator", title: "Sucka Free" },
  { artist: "Tyler, The Creator", title: "48" },
  { artist: "Tyler, The Creator", title: "HOT WIND BLOWS (feat. Lil Wayne)" },
  { artist: "Tyler, The Creator", title: "Pothole (feat. Jaden)" },
  { artist: "Tyler, The Creator", title: "Thought I Was Dead (feat. ScHoolboy Q & Santigold)" },
  { artist: "Mac Miller", title: "Knock Knock" },
  { artist: "Mac Miller", title: "Don't Mind If I Do" },
  { artist: "Mac Miller", title: "Wake Up" },
  { artist: "Mac Miller", title: "Here We Go" },
  { artist: "Mac Miller", title: "Rain (feat. Vince Staples)" },
  { artist: "Mac Miller", title: "Polo Jeans (feat. Earl Sweatshirt)" },
  { artist: "Mac Miller feat. Thundercat", title: "She Knows Too Much" },
  { artist: "Mac Miller", title: "Party On Fifth Ave." },
  { artist: "Kid Cudi", title: "Up Up & Away" },
  { artist: "Kid Cudi feat. Ty Dolla $ign", title: "Can't Shake Her" },
  { artist: "Kanye West", title: "Stronger" },
  { artist: "Kanye West", title: "Good Life (feat. T-Pain)" },
  { artist: "Kanye West", title: "Champion" },
  { artist: "Kanye West", title: "Homecoming (feat. Chris Martin)" },
  { artist: "Kanye West", title: "POWER" },
  { artist: "Kanye West", title: "Paranoid" },
  { artist: "MF DOOM", title: "Doomsday" },
  { artist: "MF DOOM", title: "All Caps" },
  { artist: "MF DOOM", title: "Rapp Snitch Knishes" },
  { artist: "MF DOOM", title: "One Beer" },
  { artist: "CZARFACE & MF DOOM", title: "Break in the Action" },
  { artist: "Viktor Vaughn (MF DOOM)", title: "Lickupon" },
  { artist: "Freddie Gibbs & The Alchemist", title: "Baby $hit" },
  { artist: "Freddie Gibbs & The Alchemist", title: "Fake Names" },
  { artist: "Freddie Gibbs & The Alchemist", title: "Mar-a-Lago" },
  { artist: "Freddie Gibbs feat. Anderson .Paak", title: "Ensalada" },
  { artist: "A$AP Rocky", title: "Sundress" },
  { artist: "A$AP Rocky feat. Gorillaz & Westside Gunn", title: "WHISKEY (RELEASE ME)" },
  { artist: "A$AP Rocky feat. Brent Faiyaz", title: "STAY HERE 4 LIFE" },
  { artist: "Outkast", title: "The Way You Move" },
  { artist: "Outkast", title: "Bowtie" },
  { artist: "Kendrick Lamar feat. SZA", title: "All The Stars" },
  { artist: "Steve Lacy feat. SZA", title: "is it cool?" },
  { artist: "Brent Faiyaz", title: "other side." },
  { artist: "Brent Faiyaz", title: "wrong faces." },
  { artist: "Brent Faiyaz", title: "four seasons." },
  { artist: "Brent Faiyaz", title: "vanilla sky." },
  { artist: "Brent Faiyaz", title: "have to." },
  { artist: "Brent Faiyaz", title: "Best Time" },
  { artist: "Brent Faiyaz", title: "Clouded" },
  { artist: "Brent Faiyaz feat. A$AP Rocky", title: "Outside All Night" },
  { artist: "Lil Nas X", title: "Panini" },
  { artist: "Post Malone feat. Doja Cat", title: "I Like You" },
  { artist: "Lupe Fiasco feat. Matthew Santos", title: "Superstar" },
  { artist: "Lupe Fiasco", title: "Samurai" },
  { artist: "Tory Lanez", title: "The Color Violet" },
  { artist: "Tory Lanez", title: "Lady Of Namek" },
  { artist: "Tory Lanez feat. Tee", title: "Pink Dolphin Sunset" },
  { artist: "Tory Lanez", title: "Ballad of a Badman" },
  { artist: "Lil Tecca", title: "Dark Thoughts" },
  { artist: "Lil Tecca", title: "Favorite Lie" },
  { artist: "Joey Valence & Brae", title: "HOOLIGANG" },
  { artist: "Joey Valence & Brae", title: "OK" },
  { artist: "Michael Jackson", title: "Chicago" },
  { artist: "Bell Biv DeVoe", title: "Poison" },
  { artist: "New Edition", title: "Mr. Telephone Man" }
];

export default songs;
